services:
  fcp-fd-auth:
    build:
      context: .
      target: production
    image: fcp-fd-auth
    container_name: fcp-fd-auth
    environment:
      APPINSIGHTS_CLOUDROLE: fcp-fd-auth-local
      APPINSIGHTS_CONNECTIONSTRING: ${APPINSIGHTS_CONNECTIONSTRING}
