# This override file should be used when running this service in isolation
# to provide dependencies and expose ports for local testing

services:
  fcp-fd-auth:
    build:
      target: development
    image: fcp-fd-auth-development
    container_name: fcp-fd-auth-development
    ports:
      - "3032:3032"
      - "9032:9229"
    volumes:
      - ./app:/home/node/app
      - ./package.json:/home/node/package.json
